### ISSUE TITLE
Cowboy Libraries

### ISSUE THREAD

**Issue by mairbek** [elixir-grpc/grpc#100]
I see that custom cowboy libraries are used since https://github.com/elixir-grpc/grpc/commit/cf74ab40e6dbc77aa6031659d0f0cc2b1768beda, could you share what was the reasoning? It blocks our adoption now...

**Comment by dbhobbs** [comment]
This makes it difficult for us to use as well.

**Comment by tony612** [comment]
There are issues in original cowboy which can result in some serious problems in gRPC. I'll send PRs to origin to see if they can be merged.

**Comment by tony612** [comment]
You can use `override` to use official deps, but I recommend using the forked before the PRs are merged.

**Comment by tony612** [comment]
And cowboy, gun, cowlib often have incompatible changes. If you can't use right versions of them, you may have some problems.

**Comment by tony612** [comment]
These are the PRs which fix problems:
```
https://github.com/ninenines/cowlib/pull/82
https://github.com/ninenines/gun/pull/198
https://github.com/ninenines/cowboy/pull/1372
https://github.com/ninenines/gun/pull/199
```

These are PRs which improve things like retrying, flow control:
```
https://github.com/ninenines/gun/pull/200
https://github.com/ninenines/cowlib/pull/83
```

**Comment by dbhobbs** [comment]
This is beginning to be a real problem for us. We use Phoenix and are not about to drop support for it. Can you at least rename the libraries since they are divergent and no longer the same?

**Comment by chulkilee** [comment]
Seems like followings are not merged yet

- https://github.com/ninenines/gun/pull/198
- https://github.com/ninenines/gun/pull/199
- https://github.com/ninenines/gun/pull/200
- https://github.com/ninenines/cowlib/pull/83

**Comment by essen** [comment]
Goes quicker with test cases. :-) But I am looking at the Gun PRs now.

**Comment by essen** [comment]
https://github.com/elixir-grpc/grpc/pull/113

**Comment by dbhobbs** [comment]
@tony612 Can this be addressed? Looks like @essen is has made some updates to `gun` and `cowlib`.

**Comment by chulkilee** [comment]
This is a deal breaker for us, as we want to have one service to service web api (phoenix), consume /provide gRPC. 😢

**Comment by essen** [comment]
I was doing this work for a customer, but am not anymore, so the PR is not likely to progress right now. Someone else should take over or you could use my services for the few hours needed to finish this. Of course I can't say whether that'll be merged after that.

**Comment by tony612** [comment]
Closing this. See https://github.com/elixir-grpc/grpc/issues/110#issuecomment-568643162
