### ISSUE TITLE
undef error when writing integration tests

### ISSUE THREAD

**Issue by BlueHotDog** [elixir-grpc/grpc#102]
I'm trying to write integration tests and getting the following error:
```
** (CaseClauseError) no case clause matching: {:error, %GRPC.RPCError{message: ":undef: [{:cow_http2_machine, :update_window2, [{:http2_machine, :client, %{}, :normal, :undefined, :undefined, %{initial_window_size: 65535}, %{}, %{initial_window_size: 65535}, 65535, 65527, 3, 0, [{:stream, 1, \"POST\", :fin, 65535, {[], []}, 0, :undefined, :nofin, 65527, :undefined, 8, :undefined}], [], [], {:state, 175, 4096, 4096, [{44, {\"server\", \"Cowboy\"}}, {65, {\"date\", \"Tue, 11 Jun 2019 15:12:04 GMT\"}}, {66, {\"content-type\", \"application/grpc+proto\"}}]}, {:state, 399, 4096, 4096, [{48, {\"content-length\", \"46\"}}, {42, {\"te\", \"trailers\"}}, {67, {\"user-agent\", \"grpc-elixir/0.4.0-alpha.2\"}}, {66, {\"content-type\", \"application/grpc+proto\"}}, {47, {\"grpc-timeout\", \"10S\"}}, {57, {\":authority\", \"localhost:59076\"}}, {72, {\":path\", \"/buff_server_grpc.AuthService/Login\"}}]}}], []}, {:gun_http2, :data_frame, 4, [file: '/Users/x/dev/buff/server/deps/gun/src/gun_http2.erl', line: 177]}, {:gun_http2, :parse, 2, [file: '/Users/x/dev/buff/server/deps/gun/src/gun_http2.erl', line: 95]}, {:gun, :connected, 3, [file: '/Users/x/dev/buff/server/deps/gun/src/gun.erl', line: 790]}, {:gen_statem, :loop_state_callback, 11, [file: 'gen_statem.erl', line: 1145]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]", status: 2}}
```

You can see the relevant code here:
 - https://github.com/BlueHotDog/buff/blob/refactor_to_email/server/test/support/grpc_integration_case.ex#L28
 - https://github.com/BlueHotDog/buff/blob/refactor_to_email/server/lib/buff_server_grpc/auth_service/server.ex
 - https://github.com/BlueHotDog/buff/blob/refactor_to_email/server/test/buff_server_grpc/auth_service_test.exs#L41

Any idea?

I've tried playing with the timeouts without any luck :(

**Comment by BlueHotDog** [comment]
Ok, more research,
When trying to use official Gun version 1.3 it works(after changing some arguments)

Maybe that helps.
Also would be very interesting in learning why the fork off off Gun

**Comment by BlueHotDog** [comment]
any update on this? somehow i can help?

**Comment by radwo** [comment]
> Also would be very interesting in learning why the fork off off Gun

Check this issue https://github.com/elixir-grpc/grpc/issues/100

**Comment by tony612** [comment]
Please see this https://github.com/elixir-grpc/grpc/issues/110#issuecomment-568643162
