### ISSUE TITLE
Gracefully handle server connection termination / shutdown ("GOAWAY").

### ISSUE THREAD

**Issue by vamsikc** [elixir-grpc/grpc#103]
We observe a crash when the connection is terminated as follows:

> (EXIT) an exception was raised:
>         ** (CaseClauseError) no case clause matching: {:error, %GRPC.RPCError{message: "error when waiting for server: {:stop, {:goaway, 75, :no_error, \"\"}, :\"Server is going away.\"}", status: 2}}

I think we should case match here, handle this and return an appropriate status code response back to the client caller (rather than status code 2 UNKNOWN):
https://github.com/elixir-grpc/grpc/blob/6edfd9cb9ce8f19dabd8a3ae68ecd48149d36c2a/lib/grpc/stub.ex#L396

What do you think @tony612 ?

**Comment by tony612** [comment]
Could you try the master branch and upgrade gun? I believe I fixed this problem in gun. Now grpc will still handle requests after GOAWAY is received.

**Comment by essen** [comment]
Please try with the following branches:

* Gun https://github.com/ninenines/gun/pull/206
* Cowboy https://github.com/ninenines/cowboy/pull/1399

**Comment by essen** [comment]
I've merged both branches.

**Comment by essen** [comment]
https://github.com/elixir-grpc/grpc/pull/113

**Comment by tony612** [comment]
Could you try 0.5.0-beta?

**Comment by polvalente** [comment]
Closing due to updates in #224 and the discussion being stale
