### ISSUE TITLE
cowboy dependency mismatch

### ISSUE THREAD

**Issue by criticalbh** [elixir-grpc/grpc#107]
Hello,

When using `elixir-grpc` on fresh mix project and trying to integrate `prometheus` with `plug_cowboy`, `cowboy` deps are mismatching. 

As a workaround I have forked `plug_cowboy` and modified `cowboy` to use one from `elixir-grpc/cowboy`: https://github.com/criticalbh/plug_cowboy/commit/32eedf8ff1963c2d592e53c7df3f1623fcbb7483
_(I have executed tests, and it behaves the same as when using original cowboy)_

I think it would be good to fork `plug_cowboy` to `elixir-grpc` organization, so we can easily track new versions of `elixir-grpc/cowboy`.

**Comment by criticalbh** [comment]
Connected with https://github.com/elixir-grpc/grpc/issues/100

**Comment by essen** [comment]
https://github.com/elixir-grpc/grpc/pull/113

**Comment by dbhobbs** [comment]
What's the status here? @tony612

**Comment by tony612** [comment]
See https://github.com/elixir-grpc/grpc/issues/110#issuecomment-568643162
