### ISSUE TITLE
idle_timeout setting doesn't work

### ISSUE THREAD

**Issue by guanwuyu234** [elixir-grpc/grpc#108]
We get following error in our client when the calling time exceeds 60s: 

`
io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
`

So we set idle_timeout in our grpc server as:

`
supervisor(GRPC.Server.Supervisor, [{DiverWeb.GrpcEndpoint, 50051, [idle_timeout: 1_000_000]}])
`

It doesn't work, we keep getting the same error message.

However, we modify `cowboy_start_args` in grpc/adapter/cowboy.ex by adding `idle_timeout: idle_timeout` in the returning map as:

````
 defp cowboy_start_args(endpoint, servers, port, opts) do
    dispatch =
      :cowboy_router.compile([
        {:_, [{:_, GRPC.Adapter.Cowboy.Handler, {endpoint, servers, Enum.into(opts, %{})}}]}
      ])

    idle_timeout = Keyword.get(opts, :idle_timeout, :infinity)

    [
      servers_name(endpoint, servers),
      %{
        num_acceptors: @default_num_acceptors,
        socket_opts: socket_opts(port, opts)
      },
      %{
        env: %{dispatch: dispatch},
        idle_timeout: idle_timeout, # add this item
        inactivity_timeout: idle_timeout, 
        settings_timeout: idle_timeout,
        stream_handlers: [:grpc_stream_h]
      }
    ]
  end
````
The idle_timeout setting can work after we re-compile the package.

I don't know if it is a bug or we doesn't set idle_timeout correctly.

**Comment by tony612** [comment]
It's a bug. I didn't realize inactivity_timeout and idle_timeout are different.
