### ISSUE TITLE
ResourceExhausted error

### ISSUE THREAD

**Issue by ferigis** [elixir-grpc/grpc#111]
hi!
When I try to reply a big response from a unary rpc call I got this error using `grpcurl`
```
  Code: ResourceExhausted
  Message: grpc: received message larger than max (4892686 vs. 4194304)
```
is there a way to handle this issue nicely or increment that `4194304` message size or something?

Thanks!

**Comment by tony612** [comment]
Is there a way to reproduce this? btw, please try master or 0.5.0-beta, which update cowboy.

**Comment by polvalente** [comment]
Closed due to lack of response
