### ISSUE TITLE
Large file internal server error

### ISSUE THREAD

**Issue by a-kinder** [elixir-grpc/grpc#120]
We have a service that processes files using gRPC, and although small files work fine, large files (evidently over ~2MB) return `{:error, %GRPC.RPCError{message: "Internal Server Error", status: 2}}`. Is there a way to up this limit, or chunk larger files so that we can process them?

**Comment by tony612** [comment]
Could you try the master or 0.5.0-beta? I believe this is already fixed because there's a test case https://github.com/elixir-grpc/grpc/blob/f9402719d86b61d1d57fed9edfaf597ec3606b65/interop/lib/interop/client.ex#L27

**Comment by polvalente** [comment]
Closing due to possible fix and lack of subsequent response
