### ISSUE TITLE
cowboy/cowlib forks 

### ISSUE THREAD

**Issue by bryanhuntesl** [elixir-grpc/grpc#122]
Are there any plans to merge the cowboy/cowlib forks upstream? I'm thinking the forks might miss out on security fixes/new functionality over time.

**Comment by vicenteortegatorres** [comment]
As an alternative, could it be possible to directly update to last cowboy/cowlib versions due to this issue https://github.com/ninenines/cowboy/pull/1393 was already fixed by the author of those libraries?

**Comment by tony612** [comment]
Sorry for the delay. See https://github.com/elixir-grpc/grpc/issues/110
