### ISSUE TITLE
[Question] Library still actively being updated?

### ISSUE THREAD

**Issue by sikanrong** [elixir-grpc/grpc#123]
We've been waiting about 9 months for a new version, specifically for a final (non-alpha) version of 0.4.0. The warning about production use of this library is really ominous. We're using it as a dependency in our `etcd_client` library, hoping that eventually gRPC would be updated to reflect stability. Should we stop hoping for that? 

I'm obliged to ask because this directly affects my business and the technical decisions we make.

**Comment by tony612** [comment]
Sorry about the delay. See https://github.com/elixir-grpc/grpc/issues/110#issuecomment-568643162

**Comment by sikanrong** [comment]
Awesome!! Thanks so much for responding - no probz about the delay
