### ISSUE TITLE
How to go about implementing bidirectional streams?

### ISSUE THREAD

**Issue by lucaspiller** [elixir-grpc/grpc#136]
I want to use this to setup a service that's defined like this. This works as long as the client streams requests, and then the server streams responses.

```
rpc BidiHello(stream HelloRequest) returns (stream HelloResponse) {}
```

In my case the roles of server and client are reversed, as I'm using this for the server to make RPC calls to the client. I want the server to start streaming requests, which the client will respond to, and then the server streams more requests as long as the stream is open.

The main issue is that there is no way to receive more requests from the client in the handler function. If we take the RouteChat example, the actual implementation should be something like this:

```
  @spec record_chat(Enumerable.t(), GRPC.Server.Stream.t()) :: any
  def route_chat(req_enum, stream) do
    note = Server.recv(req_enum)
    new_notes = Map.update(notes, key, [note], &(&1 ++ [note]))

    Enum.each(new_notes[key], fn note ->
      IO.inspect(note)
      Server.send_reply(stream, note)
    end)

    Date.update(new_notes)
    route_chat(req_enum, stream)
  end
```

Is there any way to do this now? If not, can you give me some pointers on how to go about implementing this?

**Comment by tony612** [comment]
> I want the server to start streaming requests
No, you can't let a server start the streaming requests. Please let me know if you can do this in other implements like Go, Ruby.

> no way to receive more requests from the client in the handler function
`req_enum` is a `Stream`, you can use all functions in https://hexdocs.pm/elixir/Stream.html . When you `take` one item from the stream, the server will try to receive one message.

**Comment by lucaspiller** [comment]
> No, you can't let a server start the streaming requests

Right you can't do this directly in gRPC, but the client can make a call with the signature above to open a bidirectional stream. Depending on how you handle the messages from the server on the client, you can effectively have the server stream requests to the client.

> req_enum is a Stream

Ok that's what I was missing, in Go the same parameter is used for sending and receiving so I was trying to receive on the second parameter (the output stream).

If anyone comes across this with the same issue here is an example. Given this implementation:

```
service PingPong {
  rpc PingPong (stream Pong) returns (stream Ping) {}
}
```

These two server implementations are equivalent:

```elixir
  @spec ping_pong(GRPC.Server.Stream.t(), GRPC.Server.Stream.t()) :: any
  def ping_pong(in_stream, out_stream) do
    ping_pong(in_stream, out_stream, 1)
  end

  defp ping_pong(in_stream, out_stream, id) do
    ping = Ping.new(id: id)
    GRPC.Server.send_reply(out_stream, ping)
    Logger.info("Ping #{ping.id}")

    Stream.take(in_stream, 1) |> Enum.map(fn pong ->
      Logger.info("Pong #{pong.id}")
    end)

    Process.sleep(1000)
    ping_pong(in_stream, out_stream, id + 1)
  end
```

```go
func (s *server) PingPong(stream pb.PingPong_PingPongServer) error {
	var id int32 = 1

	for {
		ping := &pb.Ping{Id: id}
		err := stream.Send(ping)
		if err != nil {
			log.Fatalf("Failed to send ping %v", err)
		}
		log.Printf("Ping %d", ping.Id)

		pong, err := stream.Recv()
		if err == io.EOF {
			log.Printf("Stream closed")
			return nil
		}

		if err != nil {
			log.Fatalf("Failed to recv pong %v", err)
		}

		log.Printf("Pong %d", pong.Id)

		time.Sleep(time.Second)
		id++
	}
}
```
