### ISSUE TITLE
Timeout in bi-drectional stream

### ISSUE THREAD

**Issue by mairbek** [elixir-grpc/grpc#141]
**Describe the bug**
After upgrading to the HEAD bi-directional RPCs started timing out. A debugging session that we ran indicates that 

```
  {s, body, req} = :cowboy_req.read_body(req, opts)
```

is timing out with a default timeout which is 15 seconds + 1. I was able to write a test that indicates the bug, https://github.com/mairbek/grpc/commit/0d92937c65f7ed1862062347e07f64e0aa8c1e18

Note that downgrading to the older version of the library fixes this issue. `cowboy_req.read_body` returns in 15 seconds.

```

14:07:23.938 [warn]  sending request {%{bindings: %{}, body_length: :undefined, cert: :undefined, has_body: true, headers: %{"content-type" => "application/grpc+proto", "te" => "trailers", "user-agent" => "grpc-elixir/0.4.0"}, host: "localhost", host_info: :undefined, method: "POST", path: "/routeguide.RouteGuide/RouteChat", path_info: :undefined, peer: {{127, 0, 0, 1}, 56062}, pid: #PID<0.272.0>, port: 56061, qs: "", ref: "GRPC.Integration.ServiceTest.FeatureServer", resp_headers: %{"content-type" => "application/grpc+proto"}, scheme: "http", sock: {{127, 0, 0, 1}, 56061}, streamid: 1, version: :"HTTP/2"}, %{}}

14:07:38.938 [warn]  done requests

14:07:38.940 [warn]  sending request {%{bindings: %{}, body_length: :undefined, cert: :undefined, has_body: true, headers: %{"content-type" => "application/grpc+proto", "te" => "trailers", "user-agent" => "grpc-elixir/0.4.0"}, host: "localhost", host_info: :undefined, method: "POST", path: "/routeguide.RouteGuide/RouteChat", path_info: :undefined, peer: {{127, 0, 0, 1}, 56062}, pid: #PID<0.272.0>, port: 56061, qs: "", ref: "GRPC.Integration.ServiceTest.FeatureServer", resp_headers: %{"content-type" => "application/grpc+proto"}, scheme: "http", sock: {{127, 0, 0, 1}, 56061}, streamid: 1, version: :"HTTP/2"}, %{}}

14:07:40.925 [warn]  done requests

14:07:40.927 [warn]  sending request {%{bindings: %{}, body_length: :undefined, cert: :undefined, has_body: true, has_sent_resp: :headers, headers: %{"content-type" => "application/grpc+proto", "te" => "trailers", "user-agent" => "grpc-elixir/0.4.0"}, host: "localhost", host_info: :undefined, method: "POST", path: "/routeguide.RouteGuide/RouteChat", path_info: :undefined, peer: {{127, 0, 0, 1}, 56062}, pid: #PID<0.272.0>, port: 56061, qs: "", ref: "GRPC.Integration.ServiceTest.FeatureServer", scheme: "http", sock: {{127, 0, 0, 1}, 56061}, streamid: 1, version: :"HTTP/2"}, %{}}

```

**To Reproduce**
https://github.com/mairbek/grpc/commit/0d92937c65f7ed1862062347e07f64e0aa8c1e18

```
mix test test/grpc/integration/service_test.exs:112
```

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Protos**
If applicable, add protos to help explain your problem.

**Versions:**
- OS:
- Erlang:
- Elixir:
- mix.lock(grpc, gun, cowboy, cowlib):

**Additional context**

**Comment by mairbek** [comment]
@tony612 could you take a look? I cannot pinpoint what caused the regression but https://github.com/elixir-grpc/grpc/pull/142 seems to be a potential fix.

**Comment by prydonius** [comment]
This appears to be the commit where cowboy was upgraded and this issue starts appearing (https://github.com/elixir-grpc/grpc/commit/43ec98549d41109b460684569f3b9a1d2dd0fa68). After downgrading cowboy to `grpc-2.6.3` and cowlib to `grpc-2.7.3`, and reverting the change to `grpc_stream_h.erl`, it works as expected.

**Comment by tony612** [comment]
I think @prydonius 's guess is right. Your PR is merged. btw, let me set the client's timeout to `:infinity` if it's a streaming RPC.

**Comment by tony612** [comment]
I created a PR to set default timeout to `:infinity` only for streaming calls. Please leave some comments.

**Comment by mairbek** [comment]
thank you for addressing!
