### ISSUE TITLE
Client side Stream lifetimes are not clear from documentation

### ISSUE THREAD

**Issue by grantwest** [elixir-grpc/grpc#145]
I have a function that is a normal request with streaming response, and these are my questions/confusions:

Should I be calling `GRPC.Stub.recv` on the stream multiple times? It feels like I should. 

The documentation mentions the `end_stream` function, then it says this:
```
The stream will be in half_closed state after this is called.
``` 
So presumably there is a way to get the stream to be `fully_closed` or something?

And lastly, the `do_call` function has this bit:
```
stream
    |> channel.adapter.send_request(message, opts)
    |> recv(opts)
```
So it calls `recv` once for you. This causes an error and does not return the stream if the server did not have any events to give the client before the timeout. This means I have to open the steam again rather than just calling `recv` again.

**Comment by tony612** [comment]
It depends on what type streaming is your RPC. There are three types:
1. Client-side streaming
2. Server-side streaming
3. bi-direction
The usage will be a little different for them. You can look at interop for examples, like the server-side streaming https://github.com/elixir-grpc/grpc/blob/master/interop/lib/interop/client.ex#L99
