### ISSUE TITLE
This library should use Plug

### ISSUE THREAD

**Issue by isaacsanders** [elixir-grpc/grpc#146]
**Is your feature request related to a problem? Please describe.**
I want to be able to use the code that myself and others have written that exists in the ecosystem.

**Describe the solution you'd like**
GRPC uses Plug as its interface.

**Describe alternatives you've considered**
None. There isn't really an alternative to this particular feature request.

**Additional context**
Plug is the community standard and is well supported.

I imagine there are challenges within the GRPC spec that might make this difficult, so I can appreciate the challenge here.

**Comment by hkrutzer** [comment]
How would that work if the protocol is not http?

**Comment by isaacsanders** [comment]
I don’t think it has to. This library would just needs to provide an interface for that allows for embedding into a Plug structure, rather than exposing its own server integration.

**Comment by hkrutzer** [comment]
How would it handle headers, cookies, body_params, query_params and other HTTP features that are in Plug?

**Comment by tony612** [comment]
I'm afraid current Plug can't(or very difficult) be used. Plug is designed for HTTP/1 and Connection is the core. But gRPC is for HTTP/2 and Stream is the core. And many things of Plug won't match with gRPC like Router and things mentioned by @hkrutzer . They are very different. You can try with this if you want, but I won't take it to my plate for the moment. Sorry about this.
