### ISSUE TITLE
Upstream gun fork

### ISSUE THREAD

**Issue by mackeyja92** [elixir-grpc/grpc#154]
Since this package depends on a fork of the gun library, is it possible to upstream those changes? There is two issues with the current system:

1. The fork is behind. I’m not sure what has changed upstream but there is quite a few commits behind.
2. The way that gRPC is specifying this dep, it actually requires an override of gun as well if the project is already using gun for other stuff, such as Tesla or MachineGun. This is problematic because we have to put in an override and also alias it to the other hex package. Eg `{:gun, "~> 2.0.0", override: true, hex: :grpc_gun}`

If these changes cannot be upstreamed, can we change the dep from `:gun` to `:grpc_gun` and avoid aliasing the hex package?

**Comment by mackeyja92** [comment]
Ah, so after some more investigation I see that the fork is up to date with a tag on the upstream. Maybe all that is needed is an updated readme on here explaining how to appropriately override this until it is merged and further explanation of why the fork.

**Comment by tony612** [comment]
Added a note in README and opened an issue for Gun.
