### ISSUE TITLE
Why GRPC.Adapter.Gun.connect/2 returns {:error, String.t()} on error?

### ISSUE THREAD

**Issue by bszaf** [elixir-grpc/grpc#159]
I would like to handle some connect errors, that are returned from `:gun` in specific way. 

Is there any reason why the error is converted to string?
https://github.com/elixir-grpc/grpc/blob/d8a58cca77a5fc106669f8ddaee634e0a3ba9267/lib/grpc/adapter/gun.ex#L68-L71

Would it be okay to return just `{:error, reason}` instead of creating String error message?

Otherwise, for compatibility reasons, can another option be added to GRPC.Adapter.Gun.connect/2, that will prevent from converting error into String?

**Comment by tony612** [comment]
String is to keep consistent with `{:error, "Error when opening connection: protocol #{proto} is not http2"}`. Let me change this.
