### ISSUE TITLE
Ideal way to test servers and clients?

### ISSUE THREAD

**Issue by jared-mackey** [elixir-grpc/grpc#162]
**Describe the question**
What is the ideal way to test our servers and clients? I have looked at the example apps and do not see any tests written there.

For clients, I'd like to just use mox if I can.

For servers, I'd like to simulate a request coming in.

What are your thoughts?

**Comment by polvalente** [comment]
@jared-mackey we're discussing adding a behaviour for clients and servers in #199 and #200 

This should enable Mox usage more easily. For now, it is already possible if you define your own behaviour and forcibly configure it. I'll close this issue in favor of that.

Let me know if this still doesn't solve your problem :)
