### ISSUE TITLE
gRPC cannot be restarted without restarting VM's state

### ISSUE THREAD

**Issue by igormq** [elixir-grpc/grpc#165]
**Describe the bug**
gRPC Runtime loads its extensions in a non idempotent way, preventing the `:grpc` application to get up when restarted without restarting the VM's state (due to the use of `:persistent_term`)

**To Reproduce**
```elixir
Application.ensure_started(:protobuf)
Application.stop(:protobuf)
Application.ensure_started(:protobuf)
> Application protobuf exited
> Extension Google.Protobuf.FileOptions#1407 already exists
```

**Expected behavior**
It should started without raising any exception

**Versions:**
- OS: MacOS
- Erlang: 22.3
- Elixir: 1.10.3
- mix.lock(grpc, gun, cowboy, cowlib):
```
cowboy": {:hex, :cowboy, "2.7.0", "91ed100138a764355f43316b1d23d7ff6bdb0de4ea618cb5d8677c93a7a2f115", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}, 
"grpc": {:git, "https://github.com/bamorim/grpc.git", "46ab2008096e44b118d831e66302d689f024ca56", [branch: "feature/introduce-get-cert"]},
"gun": {:hex, :grpc_gun, "2.0.0", "f99678a2ab975e74372a756c86ec30a8384d3ac8a8b86c7ed6243ef4e61d2729", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}], 
```

**Comment by polvalente** [comment]
This seems to be an upstream problem in protobuf, as discussed (and fixed?) in elixir-protobuf/protobuf#130

We have updated to protobuf 0.9 (and will update to 0.10 soon), so I think this issue is resolved
