### ISSUE TITLE
calling RPC fails

### ISSUE THREAD

**Issue by hmatinho** [elixir-grpc/grpc#172]
**Describe the bug**
following the example fails

**To Reproduce**
setup as in the example
when reaching call rpc with 
{:ok, channel} = GRPC.Stub.connect("localhost:50051")

fails with

19:58:33.955 [error] Unexpected event in state :domain_lookup of type :info:
{:timeout, #Reference<0.3183912324.4145283078.197184>, {:cow_http2_machine, :preface_timeout}}
{:state, #PID<0.801.0>, {:up, #Reference<0.3183912324.4145283078.197164>}, 'localhost', 50051, "http", 'localhost', 50051, [], %{http2_opts: %{settings_timeout: :infinity}, protocols: [:http2], retry: 100, retry_fun: &GRPC.Adapter.Gun.retry_fun/2, tcp_opts: [nodelay: true], transport: :tcp}, :undefined, :undefined, :gun_tcp, true, {:tcp, :tcp_closed, :tcp_error}, :undefined, :undefined, :gun_default_event_h, :undefined}

**Expected behavior**
just get a reference to channel so i can pass the request

**Versions:**
- OS: Mac OS Catalina (10.15.6)
- Erlang: Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
- Elixir: Elixir 1.10.4 (compiled with Erlang/OTP 23)
- mix.lock(grpc, gun, cowboy, cowlib):
"cowboy": {:hex, :cowboy, "2.7.0", "91ed100138a764355f43316b1d23d7ff6bdb0de4ea618cb5d8677c93a7a2f115", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}, {:ranch, "~> 1.7.1", [hex: :ranch, repo: "hexpm", optional: false]}], "hexpm", "04fd8c6a39edc6aaa9c26123009200fc61f92a3a94f3178c527b70b767c6e605"},
  "cowlib": {:hex, :cowlib, "2.9.1", "61a6c7c50cf07fdd24b2f45b89500bb93b6686579b069a89f88cb211e1125c78", [:rebar3], [], "hexpm", "e4175dc240a70d996156160891e1c62238ede1729e45740bdd38064dad476170"},
  "grpc": {:git, "https://github.com/elixir-grpc/grpc.git", "9b8bfce9ba529805ac0bd6d183bf9563a9f24b0c", []},
  "gun": {:hex, :grpc_gun, "2.0.0", "f99678a2ab975e74372a756c86ec30a8384d3ac8a8b86c7ed6243ef4e61d2729", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}], "hexpm", "03dbbca1a9c604a0267a40ea1d69986225091acb822de0b2dbea21d5815e410b"}

**Comment by ljmarks** [comment]
What's happening here is that gun's http2 state-machine is timing out while waiting for the server to send the [preface  ](https://http2.github.io/http2-spec/#ConnectionHeader). 

This should only happen after gun has initiated and established a TCP connection on the specified address/port and therefore the call to `GRPC.Stub.connect/1` should return after a TCP connection is established. You mention that the call does not return but fails with the given error message. Are you sure this is the case?

My guess would be there is something listening to TCP connections on that address but it is not a http/2 server.

**Comment by hmatinho** [comment]
@ljmarks you are absolutely right, the example in question is the one in the README.md doc step 4. of the usage part (https://github.com/elixir-grpc/grpc#usage)
 
It does output the {:ok, channel} with the correct structure and then starts to output the error messages related to gun's http2 state machine like you stated above.

Every step above has been followed I started the GRPC server in a supervised fashion as per the step 3.

**Comment by hmatinho** [comment]
My bad, the port on the tutorial was being used by another daemon on the system. 
can we perhaps have a way to raise if the server port is being used by another process ?
