### ISSUE TITLE
Crash seen on Stream reset by server, can we handle gracefully?

### ISSUE THREAD

**Issue by lizziepaquette** [elixir-grpc/grpc#188]
**Describe the bug**

We're seeing a crash when the connection is canceled. 

```
** (CaseClauseError) no case clause matching: {:error, %GRPC.RPCError{message: ":stream_error: {:stream_error, :no_error, :\"Stream reset by server.\"}", status: 13}}
    (grpc) lib/grpc/stub.ex:456: GRPC.Stub.recv_body/5
    (grpc) lib/grpc/stub.ex:427: GRPC.Stub.do_recv/2
```

**To Reproduce**
We think the client is canceling the connection and then the server resets, but we're not sure. 

**Expected behavior**
We're wondering if this case clause should propagate the error coming from the gun adapter rather than crashing. @tony612 any insight?

**Versions:**
- Elixir: 1.8.1
- mix.lock(grpc, gun, cowboy, cowlib):
-  "grpc": {:git, "https://github.com/brexhq/grpc-elixir.git", "5260f9ca0a7121d7946acb13451f82f21063b3d6", [branch: "brex-head"]},
-   "cowboy": {:hex, :cowboy, "2.7.0", "91ed100138a764355f43316b1d23d7ff6bdb0de4ea618cb5d8677c93a7a2f115", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}, {:ranch, "~> 1.7.1", [hex: :ranch, repo: "hexpm", optional: false]}], "hexpm", "04fd8c6a39edc6aaa9c26123009200fc61f92a3a94f3178c527b70b767c6e605"},
-   "cowlib": {:hex, :grpc_cowlib, "2.8.1", "ddaf77f3b89bd8e6c76df67b28a4b069688eef91c0c497a246cf9bfcdf87f7d3", [:rebar3], [], "hexpm", "0366f82719d24af4ce45a6591f52a7fc859785823fde4cd84e0dc45119b5ed89"},
- "gun": {:hex, :grpc_gun, "2.0.0", "f99678a2ab975e74372a756c86ec30a8384d3ac8a8b86c7ed6243ef4e61d2729", [:rebar3], [{:cowlib, "~> 2.8.0", [hex: :cowlib, repo: "hexpm", optional: false]}], "hexpm", "03dbbca1a9c604a0267a40ea1d69986225091acb822de0b2dbea21d5815e410b"},

**Additional context**

**Comment by polvalente** [comment]
@lizziepaquette could you validate if the main branch has indeed fixed the issue through #175? We can reopen it if the bug persists.
