### ISSUE TITLE
gRPC Web Support

### ISSUE THREAD

**Issue by sleipnir** [elixir-grpc/grpc#193]
**Describe the question**
This library support [gRPC Web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md)?
If not, are there plans to support?
If there are no plans, is there a strategy that we could implement to make this work? What would it take to make this work?

**Comment by hkrutzer** [comment]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter could be an option for you

**Comment by sleipnir** [comment]
Hello @hkrutzer thanks for replying. Yes, I know this option, and I have used it in other projects, but it would not be ideal for my current use case because I am developing a proxy and it would be desirable for this to be a feature built into it without other dependencies.
But I thank you for your suggestion.

**Comment by drowzy** [comment]
@sleipnir I just published a PR of grpc-web support. If your still interested: https://github.com/elixir-grpc/grpc/pull/206
