### ISSUE TITLE
Support more HTTP2 clients

### ISSUE THREAD

**Issue by dbernheisel** [elixir-grpc/grpc#199]
**Is your feature request related to a problem? Please describe.**
Gun is great, but there are other maintained and proven HTTP2 clients, such as [Mint](https://github.com/elixir-mint/mint) and those that build upon it like [Finch](https://hex.pm/packages/finch), [Mojito](https://hex.pm/packages/mojito), and [Tesla](https://hex.pm/packages/tesla)

**Describe the solution you'd like**
A behaviour defined for HTTP adapters. I see that there is generally one already but not documented with `@behaviour` and `@callback`.

**Describe alternatives you've considered**
n/a

**Additional context**
I'd like to use gRPC, but with HTTP2 clients I'm more familiar with and widely used.

I'll be happy to contribute a Mint client, but before I do wanted to check if the project is ready to commit to an interface.

**Comment by wingyplus** [comment]
After read the stub source, the adapter behaviour will looks like this:

```
defmodule GRPC.Adapter do
  @moduledoc """
  HTTP client adapter for GRPC.
  """

  @callback connect(GRPC.Channel.t(), any) :: {:ok, GRPC.Channel.t()} | {:error, any}

  @callback disconnect(GRPC.Channel.t()) :: {:ok, GRPC.Channel.t()} | {:error, any}

  @callback send_request(GRPC.Client.Stream.t(), binary, map) :: GRPC.Client.Stream.t()

  @callback send_headers(GRPC.Client.Stream.t(), any) :: GRPC.Client.Stream.t()

  @callback end_stream(GRPC.Client.Stream.t()) :: GRPC.Client.Stream.t()

  @callback cancel(any, GRPC.Client.Stream.stream_payload()) :: :ok | {:error, any}
end
```

I'm a bit interesting in implement adapter in Mint or Finch. And I think we can do on external repository. :D

**Comment by polvalente** [comment]
Can I work on making the HTTP Client a configurable behaviour/implementation instead of a client lock-in?
We could provide a Mint and a Gun adapter by default (Gun being for retrocompatibility), but people would be able to choose other ones if they wanted :)

**Comment by yordis** [comment]
> Can I work on making the HTTP Client a configurable behaviour/implementation instead of a client lock-in?

Strongly encourage you to make things better for the ecosystem.

You can learn from it and (maybe, we never know if the core contributors will take it 🤷🏻 ) give us all a greater experience.

So please do!

**Comment by polvalente** [comment]
I'm starting to look into this now. Hopefully a PR comes in soon

**Comment by wingyplus** [comment]
I am interested in helping this issue going forward since it has benefits in my service that I take care of. What should we start?

**Comment by polvalente** [comment]
> I am interested in helping this issue going forward since it has benefits in my service that I take care of. How do we start? 

This one has work in progress in #200 and I'll also be coordinating with what some other forks have done.

We can find another task if you can't find an issue that piques your interest

**Comment by polvalente** [comment]
Closing this in favor of #242
