### ISSUE TITLE
consider show only one type of log when using level option on logger

### ISSUE THREAD

**Issue by rands0n** [elixir-grpc/grpc#208]
**Is your feature request related to a problem? Please describe.**

When using `intercept GRPC.Logger.Server, level: :info`. I want to show only this level of the log.

If I do it now, it will transform all logs, even `info`, `warn`, and `error` to the option I specified.

**Describe the solution you'd like**

I think we could have an option, `only: true`. This will say that I want only log of this type, and not other types.

**Describe alternatives you've considered**

None.

**Additional context**

Not applicable.

**Comment by AleksandarFilipov** [comment]
Stumbled upon this; you could just "duplicate" `GRPC.Logger.Server` and modify it according to you needs.
