### ISSUE TITLE
Cannot generate a proto file

### ISSUE THREAD

**Issue by DaveElGhoul** [elixir-grpc/grpc#214]
**Describe the bug**
I'm getting a no match error when attempting to generate elixir code from a proto3 file.
```elixir
** (MatchError) no match of right hand side value: <<10, 40, 108, 105, 98, 47, 113, 108, 97, 105, 109, 95, 103, 97, 108, 108, 101, 114, 105, 101, 115, 47, 71, 82, 80, 67, 47, 103, 97, 108, 108, 101, 114, 105, 101, 115, 46, 112, 114, 111, 116, 111, 18, 9, 71, 97, 108, 
108, 101, 114, ...>>
    (protobuf 0.9.0) lib/protobuf/decoder.ex:135: Protobuf.Decoder.decode_delimited/4
    (protobuf 0.9.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
    (protobuf 0.9.0) lib/protobuf/protoc/cli.ex:48: Protobuf.Protoc.CLI.main/1
    (elixir 1.13.1) lib/kernel/cli.ex:126: anonymous fn/3 in Kernel.CLI.exec_fun/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.
```

**To Reproduce**
I suspect this is a windows issue, as I've seen a similar issue here: https://github.com/elixir-grpc/grpc/issues/23

**Expected behavior**
A ``.pb.ex`` file generated

**Versions:**
- OS: Windows 10 64-bit
- Erlang: Erlang/OTP 22
- Elixir: Elixir 1.13.1
- mix.lock(grpc, gun, cowboy, cowlib): 
      grpc, 0.5.0-beta.1
      cowboy, 2.9.0
      cowlib, 2.11.0
      gun, 2.0.0
      protobuf 0.9.0

**Additional context**
Command used: protoc --elixir_out=plugins=grpc:./ ./lib/directory1/directory2/file.proto

**Comment by wingyplus** [comment]
It seems it's the issue on protobuf  that I found a few days ago https://github.com/elixir-protobuf/protobuf/issues/279

**Comment by polvalente** [comment]
Closing because this is an upstream issue in protobuf
