### ISSUE TITLE
[CI] Run Interop tests in with the version matrix

### ISSUE THREAD

**Issue by polvalente** [elixir-grpc/grpc#223]
Currently, our interop tests only run in a specific Elixir 1.9 image.
I think it would be better to run them in a version matrix like the unit tests. Since they take long, perhaps we can use either a reduced matrix or just run them in the main branch

**Comment by wingyplus** [comment]
Let start running on the main branch with matrix support?

**Comment by wingyplus** [comment]
Or running on PR with newest OTP/Elixir version and run full matrix when merge to master branch?

**Comment by polvalente** [comment]
> Or running on PR with newest OTP/Elixir version and run full matrix when merge to master branch?

I like this alternative!
