### ISSUE TITLE
[deps] update protobuf to 0.10+

### ISSUE THREAD

**Issue by polvalente** [elixir-grpc/grpc#225]
0.10 has breaking changes which were too much for #224
We need a separate PR for that

**Comment by wingyplus** [comment]
I’ve been successfully upgrading it to 0.10 from this patch here https://github.com/wingyplus/grpc/commit/eba6f5770c1b38c3dd35dda820353355699bcc9f#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308R39.

**Comment by polvalente** [comment]
Yeah, I ended up not upgrading because it required more than just bumping deps...
Do you want to send a PR on this, @wingyplus?

**Comment by wingyplus** [comment]
Yes. I will opening it within this day. :)

**Comment by wingyplus** [comment]
Opened. :)
