### ISSUE TITLE
GRPC.Server.Adapters.Cowboy.Handler.state document is missing

### ISSUE THREAD

**Issue by wingyplus** [elixir-grpc/grpc#249]
CI complaint about Handler.state documentation is missing

![FA19CA9F-26F5-420A-B11A-2D31C713471B](https://user-images.githubusercontent.com/484530/180588674-57d1ce75-63be-4f05-82a9-95b7f5e07dbd.png)

found from PR #236

**Comment by polvalente** [comment]
This is due to moduledoc false, IIRC
