### ISSUE TITLE
Release a new version on hex

### ISSUE THREAD

**Issue by bettybas** [elixir-grpc/grpc#310]
**Is your feature request related to a problem? Please describe.**
I see quite a bit of changes, but the 0.5.0 release is released a long time ago. 

**Describe the solution you'd like**
Could we get a new release?

**Additional context**
Can't directly link to the github in mix.exs since our CI blocks that

**Comment by polvalente** [comment]
We can think about a new release, but we still have a bit to go towards what we had set for 0.6.

I'm curious about why your CI blocks GitHub.
I'd expect linking to a specific git ref at least to be considered as safe as with Hex

**Comment by bettybas** [comment]
Our CI publishes a new release to hex.pm and you can't have git dependencies in published packages afaik. I noticed some changes in the interceptors etc. and would save me a bunch of rewriting later on.

**Comment by polvalente** [comment]
I see. As luck would have it, I'm starting to have some time back to spend on gRPC this week, so I'll try to get Telemetry out, and we can ship 0.6 with that + current changes soon.

**Comment by konstantinzolotarev** [comment]
If you will be able to switch to a new `:gun, "~>2.0` dependency, it will be awesome.
It was released already. And We wouldn't be needed to override gun with grpc_gun.

**Comment by polvalente** [comment]
This is not possible due to some conflicts. There's an open PR discussing this

**Comment by polvalente** [comment]
main branch has been updated to Gun 2.0!

I still need to finish Telemetry for a new hex release, but we're inching closer to that.
