### ISSUE TITLE
Building a new release with the latest changes.

### ISSUE THREAD

**Issue by KoeusIss** [elixir-grpc/grpc#327]
**Describe the question**
Hey, are we building a release with the latest changes?

**Versions:**
- OS:
- Erlang:
- Elixir:
- mix.lock(grpc, gun, cowboy, cowlib):

**Comment by polvalente** [comment]
There are only 2 changes since the latest release: https://github.com/elixir-grpc/grpc/compare/v0.6.0...master

Are you in need of one of them?

**Comment by KoeusIss** [comment]
yes, I need the mint upgrade.

**Comment by polvalente** [comment]
v0.7.0 released to Hex :)
