### ISSUE TITLE
Add the ability to use a different webserver

### ISSUE THREAD

**Issue by conradwt** [elixir-grpc/grpc#328]
**Is your feature request related to a problem? Please describe.**
At this time, there're unintended dependencies when adding `grpc` to your `mix.exs` file.  For example, the code uses Cowboy and Cowlib but I'm looking to use Bandit.

**Describe the solution you'd like**
I thought one could use Elixir behaviors to make swapping in a different web server.

**Describe alternatives you've considered**
The alternative approach would be to fork, modify, and test with a different web server.

**Additional context**

**Comment by polvalente** [comment]
You can already implement a custom adapter for https://github.com/elixir-grpc/grpc/blob/master/lib/grpc/server/adapter.ex and configure it as the implementation to be used.

**Comment by polvalente** [comment]
I'm closing this for now because there are no plans to add a secondary implementation to the repo itself, but users can already implement and use their own.

PRs are welcome, though.

**Comment by conradwt** [comment]
@polvalente Great, this is just what I was looking for.  Thanks again for the information.

**Comment by polvalente** [comment]
Great! If you feel the documentation on how to do the implementation can be improved, please either send a PR so we can iterate on it or open another issue :)

**Comment by conradwt** [comment]
@polvalente I'm trying to learn from the documentation on the best way to complete an adapter.  However, I'm not seeing much detail at the following link:

https://hexdocs.pm/grpc/GRPC.Server.Adapter.html

I'll just file another issue.
