### ISSUE TITLE
publish version bump to hex.pm -- version wasn't bumped for deps tweak

### ISSUE THREAD

**Issue by mrluc** [elixir-grpc/grpc#332]
**Is your feature request related to a problem? Please describe.**
Doesn't install on a project that uses a more recent `mint`, because of `0.6.0`'s `{:mint, ~>1.4.2}` vs. the current `main` branch's bumped 1.5.

<img width="481" alt="image" src="https://github.com/elixir-grpc/grpc/assets/38204/2c593a00-6441-4c80-ad89-29cc6a81eb58">

**Describe the solution you'd like**
Patch version bump, publish to hex

**Describe alternatives you've considered**
Git dependency instead of hex

**Comment by polvalente** [comment]
v0.7.0 released to Hex :)
