### ISSUE TITLE
Support Grpc and flatbuffers

### ISSUE THREAD

**Issue by fire** [elixir-grpc/grpc#37]
https://grpc.io/blog/flatbuffers

https://github.com/wooga/eflatbuffers exists

There needs to be some integration with grpc-elixir.

**Comment by fire** [comment]
What are appropriate places to hook into the eflatbuffers library? I don't understand the design of grpc-elixir.

**Comment by tony612** [comment]
Most of the implementation of grpc-elixir may be related with protobuf. So you have to understand how grpc-elixir works if you want to add the flatbuffers support. But it's hard to explain the design in some words, the code is the best way. And you can refer the this doc https://grpc.io/docs/guides/wire.html. gRPC is just an HTTP/2 framework, you can use Protobuf or flatbuffers to marshal/unmarshal the data.

**Comment by odo** [comment]
Hi, main author of [eflatbuffers](https://github.com/wooga/eflatbuffers) here.
If can can help with this, I would be happy to do so!

**Comment by tony612** [comment]
I think this can be implemented by using codec https://github.com/elixir-grpc/grpc/pull/99
