### ISSUE TITLE
GRPC function that returns a stream fails with deadline exceeded or goaway

### ISSUE THREAD

**Issue by sezaru** [elixir-grpc/grpc#56]
Whenever I try to use a function that returns a stream from my GRPC LND server I get one of these 2 errors:
```
iex(20)> stream = channel |> Lnrpc.Lightning.Stub.subscribe_transactions(Lnrpc.GetTransactionsRequest.new())                 
{:error, %GRPC.RPCError{message: "deadline exceeded", status: 4}}
```
or
```
iex(22)> stream = channel |> Lnrpc.Lightning.Stub.subscribe_transactions(Lnrpc.GetTransactionsRequest.new())
{:error, %GRPC.RPCError{message: "{:stop, {:goaway, 3, :enhance_your_calm, \"too_many_pings\"}, :\"Client is going away.\"}", status: 2}}
```

The function itself is defined as:
```
rpc SubscribeTransactions (GetTransactionsRequest) returns (stream Transaction);
```

And is translated to:
```
rpc :SubscribeTransactions, Lnrpc.GetTransactionsRequest, stream(Lnrpc.Transaction)
```

Running the same request from python or nodejs works as expected, It seems like some parameter I'm using in the GRPC client or something like that, but I'm not sure.

**Comment by tony612** [comment]
Could you provide your grpc version?

**Comment by tony612** [comment]
btw, you can try this branch server-timeout to see if it's fixed already though it's WIP.

**Comment by sezaru** [comment]
Unfortunately, I'm getting the same errors with the new branch
```
iex(5)> Lnrpc.Lightning.Stub.subscribe_invoices(channel, Lnrpc.InvoiceSubscription.new())
Lnrpc.Lightning.Stub.subscribe_invoices(channel, Lnrpc.InvoiceSubscription.new())
{:error,
 %GRPC.RPCError{message: "{:stop, {:goaway, 1, :enhance_your_calm, \"too_many_pings\"}, :\"Client is going away.\"}",
  status: 2}}
iex(6)> Lnrpc.Lightning.Stub.subscribe_invoices(channel, Lnrpc.InvoiceSubscription.new())
Lnrpc.Lightning.Stub.subscribe_invoices(channel, Lnrpc.InvoiceSubscription.new())
{:error, %GRPC.RPCError{message: "deadline exceeded", status: 4}}
```

I'm not so sure what you meant by what GRPC version I'm using, do you mean the LND server GRPC version or the GRPC-Elixir version I'm using? In LND case, looking at it's dependencies, it seems it is in this revision https://github.com/grpc/grpc-go/commit/b3ddf786825de56a4178401b7e174ee332173b66 which is version 1.5.2, for the GRPC-Elixir I'm using latest from master (and now `server-timeout` version)

**Comment by sezaru** [comment]
Hello, I just captured the packages, but since the communication is encrypted, I'm not sure if it is of any help at all.

The first capture I did was without a timeout, that way the error I got everytime was
```
{:error, %GRPC.RPCError{message: "deadline exceeded", status: 4}}
```

The second capture I added a timeout of 1000000 to force the error:
```
{:error,
 %GRPC.RPCError{message: "{:stop, {:goaway, 1, :enhance_your_calm, \"too_many_pings\"}, :\"Client is going away.\"}",
  status: 2}}
```

[captures.zip](https://github.com/tony612/grpc-elixir/files/1878344/captures.zip)

**Comment by tony612** [comment]
@sezaru You can try uploading the private key. I guess Wireshark can use that to decrypt the messages. btw, the port of your grpc server is 10009, right?

**Comment by sezaru** [comment]
Hello @tony612, the private key and certificate are annexed bellow.

[key.zip](https://github.com/tony612/grpc-elixir/files/1900300/key.zip)

Also, I don't know if this would help, but if you want, I can  open internet access to my LND node and make a sample code that connects to it and reproduces the error.

So you can reproduce in your machine too.

**Comment by tony612** [comment]
@sezaru Looks like it's not a RSA private key, which is not supported by Wireshark.

**Comment by sezaru** [comment]
Hello @tony612 sorry for taking so long to reply to your message.

I was thinking, what do you think if I create a minimal elixir app that reproduces the error, send it to you and expose my server ip so you can directly connect to it with the app?

That way you would be able to directly test your fixes to it. Maybe that would help to find a solution?

**Comment by tony612** [comment]
@sezaru I guess you didn't start the service?
```
$ nc -w 5 -vz thunderpay.craftx.biz 10009
nc: connect to thunderpay.craftx.biz port 10009 (tcp) timed out: Operation now in progress
```

**Comment by sezaru** [comment]
Hello @tony612 

Sorry, someone from the team changed the dns to thunderpay.webredirect.org

Also the LND certificate was changed, so I'm sending a new elixir example app attachment with the new certificate.
[lnd_elixir.zip](https://github.com/tony612/grpc-elixir/files/2100519/lnd_elixir.zip)

I also did an equivalent example using Rust, this one will do the GRPC call and not timeout, I will attach it here too so you can use it if you think it can help.
[lnd_rust.zip](https://github.com/tony612/grpc-elixir/files/2100517/lnd_rust.zip)

Note that to run the rust code you need the rust compiler, which you can get it very easily from [here](https://rustup.rs/), and, inside the project run these commands:
```
$ cargo build
$ cargo run
```

Thanks again for the help and the amazing library!

**Comment by tony612** [comment]
@sezaru I debug a little, found the reason may be lnrpc doesn't return the response:
```
Requesting GetInfo (this call should work)

14:41:28.045 [info]  Send frame :headers {1, :nofin, [{"content-type", "application/grpc+proto"}, {"user-agent", "grpc-elixir/0.3.0-alpha.2"}, {"te", "trailers"}, {"grpc-timeout", "10S"}, {"content-length", "5"}]}

14:41:28.045 [info]  Send frame :data {1, :fin, <<0, 0, 0, 0, 0>>}

14:41:30.211 [info]  Got frame {:settings, %{}}

14:41:30.211 [info]  Send frame :settings_ack []

14:41:30.212 [info]  Got frame :settings_ack

14:41:30.213 [info]  Got frame {:window_update, 5}

14:41:30.213 [info]  Got frame {:ping, 145258749040133895}

14:41:30.213 [info]  Send frame :ping_ack 145258749040133895

14:41:30.214 [info]  Got frame {:headers, 1, :nofin, :head_fin, <<136, 95, 139, 29, 117, 208, 98, 13, 38, 61, 76, 77, 101, 100>>}

14:41:30.218 [info]  Got frame {:data, 1, :nofin, <<0, 0, 0, 1, 27, 10, 66, 48, 50, 101, 49, 53, 55, 99, 49, 100, 53, 57, 100, 54, 52, 53, 55, 48, 99, 52, 56, 102, 101, 99, 52, 52, 49, 97, 53, 55, 97, 57, 101, 53, 48, 99, 52, 102, 49, 53, ...>>}

14:41:30.218 [info]  Send frame :window_update 8000000

14:41:30.218 [info]  Send frame :window_update 1000000

14:41:30.219 [info]  Got frame {:headers, 1, :fin, :head_fin, <<64, 136, 154, 202, 200, 178, 18, 52, 218, 143, 1, 48, 64, 137, 154, 202, 200, 181, 37, 66, 7, 49, 127, 0>>}
{:ok,
 %Lnrpc.GetInfoResponse{
   alias: "PayMyCoffee",
   best_header_timestamp: 1529303951,
   block_hash: "0000000051981da21af1b4c92bd05fc836533056b839b534a790f779062f5194",
   block_height: 1325745,
   chains: ["bitcoin"],
   identity_pubkey: "02e157c1d59d64570c48fec441a57a9e50c4f15e1a701458d686d3cc426827cba9",
   num_active_channels: 2,
   num_peers: 4,
   num_pending_channels: 0,
   synced_to_chain: true,
   testnet: true,
   uris: ["02e157c1d59d64570c48fec441a57a9e50c4f15e1a701458d686d3cc426827cba9@186.249.196.225:9735"]
 }}

Now requesting Subscription to invoices (this call will timeout)

14:41:30.227 [info]  Send frame :headers {3, :nofin, [{"content-type", "application/grpc+proto"}, {"user-agent", "grpc-elixir/0.3.0-alpha.2"}, {"te", "trailers"}, {"grpc-timeout", "30S"}, {"content-length", "5"}]}

14:41:30.227 [info]  Send frame :data {3, :fin, <<0, 0, 0, 0, 0>>}

14:41:31.221 [info]  Got frame {:window_update, 5}

14:41:31.221 [info]  Got frame {:ping, 145258749040133895}

14:41:31.221 [info]  Send frame :ping_ack 145258749040133895

14:42:30.240 [info]  Application elixir_lnd exited: exited in: MyApp.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %GRPC.RPCError{message: "timeout when waiting for server", status: 4}}
```
(I turn off the ping)

From the log, we can see, after sending DATA frame(with fin), the client didn't got response from lnrpc server.

I'm still updating rust index, so I can test it later. But I don't understand why the result will be different between Rust and Elixir.

**Comment by tony612** [comment]
I ran the Rust demo but still couldn't get response from the server. So I guess it's normal except the timeout and ping too many? Maybe you can do this to keep the client waiting forever:
```
# 1. Set the keepalive timeout to infinity
      GRPC.Stub.connect(
        "thunderpay.webredirect.org:10009",
        cred: credential,
        adapter_opts: %{http2_opts: %{keepalive: :infinity}}
      )

# 2. Set the rpc timeout to infinity
channel |> Lnrpc.Lightning.Stub.subscribe_invoices(Lnrpc.InvoiceSubscription.new(), timeout: :infinity)
```

**Comment by sezaru** [comment]
Hello @tony612 I created an issue in the LND github to ask then why there is no response from the server to the stream calls.

Also, you will only receive an invoice from that function if I create an invoice request and pay for it using my node, that's why nothing was showing at all.

And thanks for that workaround, it seems to work great, thought I'm sure what are the cons of using without a timeout.

**Comment by tony612** [comment]
I think this has been fixed on master.
