### ISSUE TITLE
I keep receiving `:gun_down` and `:gun_up` error messages

### ISSUE THREAD

**Issue by ospaarmann** [elixir-grpc/grpc#61]
I use grpc-elixir to build a Dgraph client. I am using the client now to build a little side project. When running the phoenix server these messages keep popping up in my log every couple of seconds.

Most of the message comes from my client. But I am wondering if this behavior is normal. It seems as if the connection breaks every couple of seconds and gun then re-connects. 

[The gun docs state: ](https://github.com/ninenines/gun/blob/104ef37f1869616b7b2d0a303838fc4562a1b7b6/doc/src/guide/connect.asciidoc)

> When the connection is lost, Gun will send a gun_down message indicating the current protocol, the reason the connection was lost and two list of stream references.
> 
> The first list indicates open streams that may have been processed by the server. The second list indicates open streams that the server did not process.
> 

I could also handle these messages on my side but I first want to figure out what is going on.

Maybe this is not the right place to post this and I will open an issue over at the gun repo. But I thought I give it a try and you know more about this.

```
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_down, #PID<0.288.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_down, #PID<0.287.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_down, #PID<0.286.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_down, #PID<0.284.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_down, #PID<0.285.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_up, #PID<0.288.0>, :http2}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_up, #PID<0.287.0>, :http2}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_up, #PID<0.285.0>, :http2}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_up, #PID<0.284.0>, :http2}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_up, #PID<0.286.0>, :http2}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_down, #PID<0.288.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_down, #PID<0.287.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_down, #PID<0.284.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_down, #PID<0.286.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_down, #PID<0.285.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_up, #PID<0.288.0>, :http2}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_up, #PID<0.286.0>, :http2}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_up, #PID<0.284.0>, :http2}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_up, #PID<0.287.0>, :http2}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_up, #PID<0.285.0>, :http2}
```

**Comment by tony612** [comment]
How do you manage your connections? Do you create a connection every time you need one?

**Comment by ospaarmann** [comment]
I use connection pools with DBConnection and Poolboy. I have a pool of 5 connections. So they all die and then are being re-established.

**Comment by ospaarmann** [comment]
To be a bit more precise: This is the module that handles the connection (besides other things):

```elixir
defmodule ExDgraph.Protocol do
  @moduledoc """
  Implements callbacks required by DBConnection.

  Each callback receives an open connection as a state.
  """

  use DBConnection
  use Retry

  require Logger

  alias ExDgraph.Api
  alias ExDgraph.{Exception, MutationStatement, OperationStatement, QueryStatement}

  @doc "Callback for DBConnection.connect/1"
  def connect(_opts) do
    host = to_charlist(ExDgraph.config(:hostname))
    port = ExDgraph.config(:port)

    opts = set_ssl_opts()

    case GRPC.Stub.connect("#{host}:#{port}", opts) do
      {:ok, channel} ->
        {:ok, channel}

      _ ->
        Logger.error("ExDgraph: Connection Failed")
        {:error, ExDgraph.Error}
        # TODO: Proper error handling
    end
  end

  @doc "Callback for DBConnection.checkout/1"
  def checkout(state) do
    {:ok, state}
    # TODO: Proper checkout. Only placeholder callback
  end

  @doc "Callback for DBConnection.checkin/1"
  def checkin(state) do
    {:ok, state}
    # TODO: Proper checkout. Only placeholder callback
  end

  @doc "Callback for DBConnection.disconnect/1"
  def disconnect(_err, state) do
  end

  @doc "Callback for DBConnection.handle_begin/1"
  def handle_begin(_opts, state) do
  end

  @doc "Callback for DBConnection.handle_rollback/1"
  def handle_rollback(_opts, state) do
  end

  @doc "Callback for DBConnection.handle_commit/1"
  def handle_commit(_opts, state) do
  end

  @doc "Callback for DBConnection.handle_execute/1"
  def handle_execute(query, params, opts, channel) do
    # only try to reconnect if the error is about the broken connection
    with {:disconnect, _, _} <- execute(query, params, opts, channel) do
      [
        delay: delay,
        factor: factor,
        tries: tries
      ] = ExDgraph.config(:retry_linear_backoff)

      delay_stream =
        delay
        |> lin_backoff(factor)
        |> cap(ExDgraph.config(:timeout))
        |> Stream.take(tries)

      retry with: delay_stream do
        with {:ok, channel} <- connect([]),
             {:ok, channel} <- checkout(channel) do
          execute(query, params, opts, channel)
        end
      end
    end
  end

  def handle_info(msg, state) do
    Logger.error(fn ->
      [inspect(__MODULE__), ?\s, inspect(self()), " received unexpected message: " | inspect(msg)]
    end)

    {:ok, state}
  end

  defp execute(%QueryStatement{statement: statement}, params, _, channel) do
    request = ExDgraph.Api.Request.new(query: statement)

    case ExDgraph.Api.Dgraph.Stub.query(channel, request) do
      {:ok, res} ->
        {:ok, res, channel}

      {:error, f} ->
        raise Exception, code: f.status, message: f.message
    end
  rescue
    e ->
      {:error, e, channel}
  end

  defp execute(%MutationStatement{statement: statement, set_json: set_json}, params, _, channel) do
    # Build request
    cond do
      statement != "" and set_json == "" ->
        request = ExDgraph.Api.Mutation.new(set_nquads: statement, commit_now: true)

      set_json != "" and set_json != "" ->
        request = ExDgraph.Api.Mutation.new(set_json: set_json, commit_now: true)

      statement != "" and set_json != "" ->
        raise Exception, code: 2, message: "Both set_json and statement defined"
    end

    case ExDgraph.Api.Dgraph.Stub.mutate(channel, request) do
      {:ok, res} ->
        {:ok, res, channel}

      {:error, f} ->
        raise Exception, code: f.status, message: f.message
    end
  rescue
    e ->
      {:error, e, channel}
  end

  defp execute(
         %OperationStatement{drop_all: drop_all, schema: schema, drop_attr: drop_attr},
         params,
         _,
         channel
       ) do
    operation = Api.Operation.new(drop_all: drop_all, schema: schema, drop_attr: drop_attr)

    case ExDgraph.Api.Dgraph.Stub.alter(channel, operation) do
      {:ok, res} ->
        {:ok, res, channel}

      {:error, f} ->
        raise Exception, code: f.status, message: f.message
    end
  rescue
    e ->
      {:error, e, channel}
  end

  defp configure_ssl(ssl_opts \\ []) do
    case ExDgraph.config(:ssl) do
      true ->
        add_ssl_file(ssl_opts, :cacertfile)

      false ->
        ssl_opts
    end
  end

  defp configure_tls_auth(ssl_opts \\ []) do
    case ExDgraph.config(:tls_client_auth) do
      true ->
        ssl_opts
        |> add_ssl_file(:certfile)
        |> add_ssl_file(:keyfile)
        |> add_ssl_file(:certfile)

      false ->
        ssl_opts
    end
  end

  defp add_ssl_file(ssl_opts \\ [], type) do
    Keyword.put(ssl_opts, type, validate_tls_file(type, ExDgraph.config(type)))
  end

  defp validate_tls_file(type, path) do
    case File.exists?(path) do
      true ->
        path

      false ->
        raise Exception,
          code: 2,
          message: "SSL configuration error. File #{type} '#{ExDgraph.config(type)}' not found"
    end
  end

  defp set_ssl_opts(opts \\ []) do
    if ExDgraph.config(:ssl) || ExDgraph.config(:tls_client_auth) do
      ssl_opts =
        configure_ssl()
        |> configure_tls_auth()

      Keyword.put(opts, :cred, GRPC.Credential.new(ssl: ssl_opts))
    else
      opts
    end
  end
end
```

**Comment by ospaarmann** [comment]
Hey @tony612, getting back to this:

> Do you create a connection every time you need one?

As I understand the connection should be established and then keep alive unless something fails. So if I have a pool of five connections they should stay alive for as long as possible. If one fails my Poolboy worker will fire up a new one. 

Right now all five fail simultaneously. And it happens regularly every 5-10 seconds. This doesn't seem right to me. But maybe I also got something wrong.

Any help is greatly appreciated!

**Comment by ospaarmann** [comment]
Hi @tony612 ,

I profiled gun and gun_http2 to see what is going on. Server is dropping the connection with `{goaway,0,enhance_your_calm,<<"too_many_pings">>}`.

That means the `keepalive` value for gun needs to be increased. 5000ms between pings seems to be too little. 

This is atm not configurable in grpc-elixir. I would suggest to extend the grpc-elixir configuration to be able to pass in configuration for gun. I can create a PR for that but I wanted to talk to you first what you think about this and how you would approach it.

Thanks!

Full trace can be found here: https://gist.github.com/ospaarmann/c592fa984f775810b2698bf0b4d82228

**Comment by tony612** [comment]
The keepalive timeout is supported like:
```
GRPC.Stub.connect("addr", adapter_opts: %{http2_opts: %{keepalive: 10000}})
```

**Comment by guisehn** [comment]
I'm having the same issue when connecting an Elixir client to a Ruby client. I think I was able to figure out what's happening.

The default config values for gRPC keepalive as I'm writing now are:

- `GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS`: false
- `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA`: 2
- `GRPC_ARG_HTTP2_MAX_PING_STRIKES`: 2

Reference: https://github.com/grpc/grpc/blob/master/doc/keepalive.md#defaults-values

This means that by default, a gRPC server **does not** expect to receive keepalive packets when there are no RPC calls happening (because `KEEPALIVE_PERMIT_WITHOUT_CALLS` = `false`). It will accept up to 2 keepalive pings when no RPC calls are happening (`MAX_PINGS_WITHOUT_DATA`), and if it receives 2 more besides that (`MAX_PING_STRIKES`), it'll close the connection with `too_many_pings`.

Gun has a default keepalive of 5s ([ref](https://github.com/elixir-grpc/gun/blob/fcd889a598ff90aab21f24fc3ca1a304dad00b0a/src/gun_http2.erl#L124)) no matter if RPC calls are being made or not. So, if your client stays for 20s without making any RPC call, Gun sends 4 keepalive packets and the server will close the connection with `too_many_pings`.

Changing the `keepalive` period as @tony612 suggested on https://github.com/elixir-grpc/grpc/issues/61#issuecomment-397965189 will increase the tolerance period before shutting down the connection, but not completely solve the problem.

It seems like the only way to solve the problem for good if you have a channel that won't receive calls periodically is to set the channel arg `GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS` to `1` (`true`), but I couldn't find a way to do that. [Opened a new issue](https://github.com/elixir-grpc/grpc/issues/213) asking about it.
