### ISSUE TITLE
Any good way to handle gun_down/gun_up messages?

### ISSUE THREAD

**Issue by zhongwencool** [elixir-grpc/grpc#74]
Gun is always **connected**. It will maintain a permanent connection to the server, reopening it as soon as the server closes it, saving time for the requests that come in.
But 
1. The network maybe disconnect for sometime. 
2. The server disconnect the client for some reason, such as
   etcd v3 grpc server will disconnect client when client ping server 5 time without other request.

Gun will reconnect as soon as possible. and report `gun_down`/`gun_up` messages to owner.
https://github.com/ninenines/gun/blob/master/src/gun.erl#L651
Is any good way to handle those messages? 
Maybe discarded them? but I don't find a good time to discarded?

**Comment by jrichocean** [comment]
same here, is there a config setting to disable the gun server auto-reconnect?

**Comment by jrichocean** [comment]
connected to #103
