### ISSUE TITLE
Easy way to stub/mock clients?

### ISSUE THREAD

**Issue by syfgkjasdkn** [elixir-grpc/grpc#83]
👋

I wonder if there is an easy way to make the client (stub) like

```elixir
defmodule Tron.Client do
  use GRPC.Stub, service: Tron.Wallet.Service
end
```
return preconfigured responses without going over the network in a test env?

**Comment by radwo** [comment]
👋 seika, we had the same issue and create this [function registry](https://github.com/renderedtext/fun-registry), it works great for us, I hope you will enjoy it too

**Comment by radwo** [comment]
@syfgkjasdkn please check our new lib https://github.com/renderedtext/grpc-mock

**Comment by syfgkjasdkn** [comment]
@radwo Thank you so much! That looks very useful. I was actually using `mox` before for mocking an abstraction on top of the gRPC stub, but now I'll switch to your lib, I think.

**Comment by tony612** [comment]
I found another lib https://github.com/edgurgel/mimic. You can try it.
