### ISSUE TITLE
Grpc connection pooling

### ISSUE THREAD

**Issue by shiroyasha** [elixir-grpc/grpc#85]
I am opening this issue because I am not 100% sure about best practices for managing GRPC connections.

Currently I see several ways:

- Use one connection for all requests. This has a drawback that it will send all requests to a single upstream connection (pod) in a Kubernetes environment as describe here: https://mycodesmells.com/post/pooling-grpc-connections.

- Create a new connection for each requests. This is the approach we use currently, but it might cause some issues:
   - it is slower (and it might cause strain on the network)
   - if we don't close the connection we get :gun_up, :gun_down messages

- Use connection pooling with libraries like poolboy. As far as I understand this is the best way to use Gprc connections, but it requires extra setup and complexity around connections. Maybe we could write a library that handles this complexity?

I'm looking forward to your feedback on this issues. Also, let us know if we can help in any way possible.

**Comment by tony612** [comment]
I prefer the first or the third.

As official gRPC implementation and HTTP/2 spec show, I think the first is enough. But there're still problems for Elixir, like reconnecting(I'm investigating this recently), performance testing. Yeah, it's indeed a big problem for load balancing in HTTP/2(long connection). But even if we use pool, the problem still exists. There're recommendations for load balancing https://grpc.io/blog/loadbalancing#recommendations-and-best-practices. The [client-side LB](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md) needs some changes to transport layer and has not been implemented in Elixir.

For the third. I think you can have a try before I confirm one connection is OK.

**Comment by tony612** [comment]
btw, for load balancing, I recommend personally you can try Envoy if it's not a big problem to import it to your infrastructure. It works pretty well in production.

**Comment by shiroyasha** [comment]
Thanks for the detailed answer.

I'm experimenting with several setups at the moment and will report if I learn something interesting.

**Comment by zbye** [comment]
@tony612  I encountered a problem when deploying envoy as font-gateway when dealing with grpc laod balance， https://github.com/envoyproxy/envoy/issues/5700 . Can give some ideas or guidance ? Maybe there exists some problems in my configuration file or others；

**Comment by mackeyja92** [comment]
+1 for connection pooling. Currently doing #2 and it is indeed suboptimal

**Comment by alex88** [comment]
If anyone is interested I've open sourced a small library that I use internally that does the connection pooling https://hex.pm/packages/grpc_client_pool
Any advice/complaint/suggestion is very welcome!

**Comment by frekw** [comment]
I actually think connection pooling is the wrong path to take. The point of HTTP/2 is to be able to multiplex several calls over a single connection. And connection pools are basically about guarding access to a set of shared resources.

Just keeping multiple connections open, monitoring their status and spreading the load across them should be fine and won't introduce the unnecessary contention a connection pool would.

**Comment by mackeyja92** [comment]
I agree with @frekw here. 

You can use registries here as a pool since you don’t want to lock the connection from being multiplexed on. A registry that is `host` -> `channel` would be sufficient. Enabling duplicate keys could allow you to have multiple connections in here and then you can just do something like `Enum.random(channels)` on the results of your registry select call and that would probably be sufficient. 

However, if you’re in an environment where you have multiple deployments of a downstream service, such as kubernetes, you might want to get a bit smarter about how you load balance your channels. You don’t want to send all requests down the same channel as you won’t be load balancing properly. So you’d either have to manage that yourself in code or use a smart service mesh / proxy such as Linkerd.

**Comment by guisehn** [comment]
We have released a library today that adds support for keeping a pool of channels with `elixir-grpc` allowing multiplexing (it uses a routing pool with round-robin instead of checkout pool):

Check out ConnGRPC: https://www.github.com/therealreal/conn_grpc

**Comment by polvalente** [comment]
@guisehn if it's of your interest to fast track a new release, please find me on the Elixir Slack so that we can devise a plan for that :)

We're close to one, but I'm doing this in my free time so it goes slower that I'd like.
